//! AgentDesignPanel — an agent-assisted design and planning panel.
//!
//! Allows users to describe design requirements and have AI agents
//! generate architecture suggestions, component trees, data flow diagrams,
//! and wireframe descriptions. Supports design review workflows.

use dioxus::prelude::*;

/// A design suggestion generated by an AI agent.
#[derive(Clone, PartialEq, Debug)]
pub struct DesignSuggestion {
    pub id: String,
    pub title: String,
    pub description: String,
    pub category: String,
    pub priority: String,
    pub details: Vec<String>,
}

/// Props for the AgentDesignPanel component.
#[derive(Clone, PartialEq, Props)]
pub struct AgentDesignPanelProps {
    pub suggestions: Vec<DesignSuggestion>,
    pub on_generate_design: EventHandler<String>,
    pub on_implement: EventHandler<String>,
    pub on_request_review: EventHandler<String>,
}

/// Panel for agent-assisted design and architecture.
#[component]
pub fn AgentDesignPanel(props: AgentDesignPanelProps) -> Element {
    let mut prompt = use_signal(|| String::new());
    let mut active_tab = use_signal(|| "suggestions".to_string());

    let handle_generate = move |_| {
        let text = prompt().trim().to_string();
        if !text.is_empty() {
            props.on_generate_design.call(text);
            prompt.set(String::new());
        }
    };

    let design_count = props.suggestions.len();

    rsx! {
        div {
            class: "agent-design-panel",
            style: "
                background: var(--q-surface, #1a1a2e);
                border: 1px solid var(--q-surface-border, #333);
                border-radius: 12px;
                padding: 1.25rem;
                display: flex;
                flex-direction: column;
                gap: 1rem;
            ",

            // Header
            div {
                style: "
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                ",
                div {
                    style: "display: flex; align-items: center; gap: 0.5rem;",
                    span { style: "font-size: 1.1rem;", "🎨" }
                    h2 {
                        style: "
                            font-size: 1rem;
                            font-weight: 600;
                            margin: 0;
                            color: var(--q-text, #e0e0e0);
                        ",
                        "Design Agent"
                    }
                }
                span {
                    style: "
                        font-size: 0.75rem;
                        padding: 0.15rem 0.45rem;
                        border-radius: 4px;
                        background: rgba(0, 206, 201, 0.15);
                        color: var(--q-accent, #00cec9);
                        font-weight: 500;
                    ",
                    "Architecture AI"
                }
            }

            // Tabs
            div {
                style: "
                    display: flex;
                    gap: 0.25rem;
                    border-bottom: 1px solid var(--q-surface-border, #333);
                    padding-bottom: 0.5rem;
                ",
                TabButton {
                    label: "Suggestions",
                    count: design_count,
                    is_active: active_tab() == "suggestions",
                    on_click: move || active_tab.set("suggestions".to_string()),
                },
                TabButton {
                    label: "Architecture",
                    count: 0,
                    is_active: active_tab() == "architecture",
                    on_click: move || active_tab.set("architecture".to_string()),
                },
                TabButton {
                    label: "Components",
                    count: 0,
                    is_active: active_tab() == "components",
                    on_click: move || active_tab.set("components".to_string()),
                },
            }

            // Prompt input
            div {
                style: "
                    display: flex;
                    gap: 0.5rem;
                ",
                input {
                    placeholder: "Describe a design or architecture task...",
                    value: prompt(),
                    oninput: move |e| prompt.set(e.value()),
                    style: "
                        flex: 1;
                        padding: 0.55rem 0.75rem;
                        border-radius: 8px;
                        border: 1px solid var(--q-surface-border, #333);
                        background: var(--q-bg, #0f0f1a);
                        color: var(--q-text, #e0e0e0);
                        font-size: 0.85rem;
                        outline: none;
                    "
                }
                button {
                    onclick: move |_| handle_generate(),
                    style: "
                        padding: 0.55rem 1rem;
                        border-radius: 8px;
                        border: none;
                        background: var(--q-accent, #00cec9);
                        color: #fff;
                        font-size: 0.85rem;
                        font-weight: 500;
                        cursor: pointer;
                        white-space: nowrap;
                    ",
                    "Generate"
                }
            }

            // Suggestions tab content
            if active_tab() == "suggestions" {
                div {
                    style: "
                        display: flex;
                        flex-direction: column;
                        gap: 0.6rem;
                        max-height: 400px;
                        overflow-y: auto;
                    ",
                    if props.suggestions.is_empty() {
                        div {
                            style: "
                                text-align: center;
                                padding: 2rem;
                                color: var(--q-text-muted, #555);
                                font-size: 0.85rem;
                            ",
                            "Describe a design task to get AI-powered suggestions."
                        }
                    } else {
                        for suggestion in &props.suggestions {
                            DesignSuggestionCard {
                                suggestion: suggestion.clone(),
                                on_implement: {
                                    let id = suggestion.id.clone();
                                    move || props.on_implement.call(id.clone())
                                },
                                on_review: {
                                    let id = suggestion.id.clone();
                                    move || props.on_request_review.call(id.clone())
                                }
                            }
                        }
                    }
                }
            }

            // Architecture tab (placeholder)
            if active_tab() == "architecture" || active_tab() == "components" {
                div {
                    style: "
                        text-align: center;
                        padding: 3rem;
                        color: var(--q-text-muted, #555);
                        font-size: 0.85rem;
                    ",
                    "Describe your architecture requirements and the AI will generate component trees and data flow diagrams."
                }
            }
        }
    }
}

/// A tab button for the design panel.
#[component]
fn TabButton(label: String, count: usize, is_active: bool, on_click: EventHandler<()>) -> Element {
    rsx! {
        button {
            onclick: move |_| on_click.call(()),
            style: if is_active {
                "
                    padding: 0.35rem 0.85rem;
                    border-radius: 6px;
                    border: none;
                    background: var(--q-primary, #6c5ce7);
                    color: #fff;
                    font-size: 0.8rem;
                    font-weight: 500;
                    cursor: pointer;
                    transition: all 0.2s;
                "
            } else {
                "
                    padding: 0.35rem 0.85rem;
                    border-radius: 6px;
                    border: none;
                    background: transparent;
                    color: var(--q-text-secondary, #888);
                    font-size: 0.8rem;
                    font-weight: 500;
                    cursor: pointer;
                    transition: all 0.2s;
                "
            },
            span { "{label}" }
            if count > 0 {
                span {
                    style: "
                        margin-left: 0.35rem;
                        font-size: 0.7rem;
                        opacity: 0.8;
                    ",
                    "({count})"
                }
            }
        }
    }
}

/// A single design suggestion card.
#[component]
fn DesignSuggestionCard(
    suggestion: DesignSuggestion,
    on_implement: EventHandler<()>,
    on_review: EventHandler<()>,
) -> Element {
    let priority_color = match suggestion.priority.as_str() {
        "high" => "#ff4757",
        "medium" => "#fdcb6e",
        "low" => "#636e72",
        _ => "#636e72",
    };

    rsx! {
        div {
            class: "design-suggestion-card",
            style: "
                background: var(--q-bg, #0f0f1a);
                border: 1px solid var(--q-surface-border, #333);
                border-radius: 8px;
                padding: 0.85rem;
            ",

            // Header
            div {
                style: "
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                    margin-bottom: 0.4rem;
                ",
                div {
                    style: "
                        display: flex;
                        align-items: center;
                        gap: 0.5rem;
                    ",
                    span {
                        style: "
                            font-size: 0.7rem;
                            padding: 0.1rem 0.4rem;
                            border-radius: 3px;
                            background: var(--q-surface-border, #333);
                            color: var(--q-text-secondary, #888);
                            text-transform: uppercase;
                        ",
                        "{suggestion.category}"
                    }
                    h4 {
                        style: "
                            font-size: 0.85rem;
                            font-weight: 500;
                            margin: 0;
                            color: var(--q-text, #e0e0e0);
                        ",
                        "{suggestion.title}"
                    }
                }
                span {
                    style: "
                        font-size: 0.7rem;
                        padding: 0.1rem 0.4rem;
                        border-radius: 3px;
                        background: {priority_color}22;
                        color: {priority_color};
                        border: 1px solid {priority_color}44;
                        text-transform: uppercase;
                        font-weight: 500;
                    ",
                    "{suggestion.priority}"
                }
            }

            // Description
            p {
                style: "
                    font-size: 0.78rem;
                    color: var(--q-text-secondary, #888);
                    margin: 0 0 0.5rem 0;
                    line-height: 1.45;
                ",
                "{suggestion.description}"
            }

            // Details list
            if !suggestion.details.is_empty() {
                ul {
                    style: "
                        margin: 0 0 0.5rem 0;
                        padding-left: 1.25rem;
                        font-size: 0.78rem;
                        color: var(--q-text-secondary, #888);
                    ",
                    for detail in &suggestion.details {
                        li { "{detail}" }
                    }
                }
            }

            // Action buttons
            div {
                style: "
                    display: flex;
                    gap: 0.5rem;
                    margin-top: 0.5rem;
                ",
                button {
                    onclick: move |_| on_implement.call(()),
                    style: "
                        padding: 0.3rem 0.7rem;
                        border-radius: 6px;
                        border: none;
                        background: var(--q-primary, #6c5ce7);
                        color: #fff;
                        font-size: 0.75rem;
                        font-weight: 500;
                        cursor: pointer;
                    ",
                    "Implement"
                }
                button {
                    onclick: move |_| on_review.call(()),
                    style: "
                        padding: 0.3rem 0.7rem;
                        border-radius: 6px;
                        border: 1px solid var(--q-primary, #6c5ce7);
                        background: transparent;
                        color: var(--q-primary, #6c5ce7);
                        font-size: 0.75rem;
                        font-weight: 500;
                        cursor: pointer;
                    ",
                    "Request Review"
                }
            }
        }
    }
}
