//! AgentTaskPanel — an agent-assisted task creation and management panel.
//!
//! Allows users to describe tasks in natural language, have AI agents
//! decompose them into actionable items with estimates, and assign them
//! to the appropriate actor (human or agent).

use dioxus::prelude::*;

/// A task suggested or generated by an AI agent.
#[derive(Clone, PartialEq, Debug)]
pub struct AgentTaskItem {
    pub id: String,
    pub title: String,
    pub description: String,
    pub estimated_hours: f64,
    pub required_skills: Vec<String>,
    pub suggested_assignee: Option<String>,
    pub can_be_agent: bool,
}

/// Props for the AgentTaskPanel component.
#[derive(Clone, PartialEq, Props)]
pub struct AgentTaskPanelProps {
    pub tasks: Vec<AgentTaskItem>,
    pub on_decompose: EventHandler<String>,
    pub on_accept: EventHandler<String>,
    pub on_assign_to_agent: EventHandler<String>,
}

/// Panel for agent-assisted task management.
#[component]
pub fn AgentTaskPanel(props: AgentTaskPanelProps) -> Element {
    let mut prompt = use_signal(|| String::new());
    let mut expanded = use_signal(|| None::<String>);

    let handle_decompose = move |_| {
        let text = prompt().trim().to_string();
        if !text.is_empty() {
            props.on_decompose.call(text);
            prompt.set(String::new());
        }
    };

    rsx! {
        div {
            class: "agent-task-panel",
            style: "
                background: var(--q-surface, #1a1a2e);
                border: 1px solid var(--q-surface-border, #333);
                border-radius: 12px;
                padding: 1.25rem;
                display: flex;
                flex-direction: column;
                gap: 1rem;
            ",

            // Header
            div {
                style: "
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                ",
                div {
                    style: "display: flex; align-items: center; gap: 0.5rem;",
                    span { style: "font-size: 1.1rem;", "📋" }
                    h2 {
                        style: "
                            font-size: 1rem;
                            font-weight: 600;
                            margin: 0;
                            color: var(--q-text, #e0e0e0);
                        ",
                        "Agent Task Assistant"
                    }
                }
                span {
                    style: "
                        font-size: 0.75rem;
                        padding: 0.15rem 0.45rem;
                        border-radius: 4px;
                        background: rgba(0, 206, 201, 0.15);
                        color: var(--q-accent, #00cec9);
                        font-weight: 500;
                    ",
                    "AI-Powered"
                }
            }

            // Decompose prompt
            div {
                style: "
                    display: flex;
                    gap: 0.5rem;
                ",
                input {
                    placeholder: "Describe a task or goal to decompose...",
                    value: prompt(),
                    oninput: move |e| prompt.set(e.value()),
                    style: "
                        flex: 1;
                        padding: 0.55rem 0.75rem;
                        border-radius: 8px;
                        border: 1px solid var(--q-surface-border, #333);
                        background: var(--q-bg, #0f0f1a);
                        color: var(--q-text, #e0e0e0);
                        font-size: 0.85rem;
                        outline: none;
                    "
                }
                button {
                    onclick: move |_| handle_decompose(),
                    style: "
                        padding: 0.55rem 1rem;
                        border-radius: 8px;
                        border: none;
                        background: var(--q-accent, #00cec9);
                        color: #fff;
                        font-size: 0.85rem;
                        font-weight: 500;
                        cursor: pointer;
                        white-space: nowrap;
                    ",
                    "Decompose"
                }
            }

            // Suggested tasks
            div {
                style: "
                    display: flex;
                    flex-direction: column;
                    gap: 0.6rem;
                ",
                if props.tasks.is_empty() {
                    div {
                        style: "
                            text-align: center;
                            padding: 2rem;
                            color: var(--q-text-muted, #555);
                            font-size: 0.85rem;
                        ",
                        "Describe a task and the AI will decompose it into actionable items."
                    }
                } else {
                    for task in &props.tasks {
                        let is_expanded = expanded() == Some(task.id.clone());
                        AgentTaskCard {
                            task: task.clone(),
                            is_expanded,
                            on_toggle: {
                                let id = task.id.clone();
                                move || {
                                    if expanded() == Some(id.clone()) {
                                        expanded.set(None);
                                    } else {
                                        expanded.set(Some(id.clone()));
                                    }
                                }
                            },
                            on_accept: {
                                let id = task.id.clone();
                                move || props.on_accept.call(id.clone())
                            },
                            on_assign_agent: {
                                let id = task.id.clone();
                                move || props.on_assign_to_agent.call(id.clone())
                            }
                        }
                    }
                }
            }
        }
    }
}

/// A single AI-suggested task card.
#[component]
fn AgentTaskCard(
    task: AgentTaskItem,
    is_expanded: bool,
    on_toggle: EventHandler<()>,
    on_accept: EventHandler<()>,
    on_assign_agent: EventHandler<()>,
) -> Element {
    rsx! {
        div {
            class: "agent-task-card",
            style: "
                background: var(--q-bg, #0f0f1a);
                border: 1px solid var(--q-surface-border, #333);
                border-radius: 8px;
                padding: 0.75rem;
            ",

            // Title row
            div {
                style: "
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                    cursor: pointer;
                ",
                onclick: move |_| on_toggle.call(()),
                div {
                    style: "display: flex; align-items: center; gap: 0.5rem;",
                    span { style: "font-size: 0.85rem;", "☐" }
                    span {
                        style: "
                            font-size: 0.85rem;
                            font-weight: 500;
                            color: var(--q-text, #e0e0e0);
                        ",
                        "{task.title}"
                    }
                }
                div {
                    style: "
                        display: flex;
                        align-items: center;
                        gap: 0.75rem;
                    ",
                    if task.can_be_agent {
                        span {
                            style: "
                                font-size: 0.65rem;
                                padding: 0.1rem 0.35rem;
                                border-radius: 3px;
                                background: rgba(0, 206, 201, 0.12);
                                color: var(--q-accent, #00cec9);
                            ",
                            "🤖 Agent-ready"
                        }
                    }
                    span {
                        style: "
                            font-size: 0.75rem;
                            color: var(--q-text-muted, #555);
                        ",
                        "~{task.estimated_hours}h"
                    }
                    span { "{if is_expanded { \"▲\" } else { \"▼\" }}" }
                }
            }

            // Expanded details
            if is_expanded {
                div {
                    style: "
                        margin-top: 0.75rem;
                        display: flex;
                        flex-direction: column;
                        gap: 0.5rem;
                    ",
                    p {
                        style: "
                            font-size: 0.8rem;
                            color: var(--q-text-secondary, #888);
                            margin: 0;
                        ",
                        "{task.description}"
                    }

                    // Skills
                    if !task.required_skills.is_empty() {
                        div {
                            style: "
                                display: flex;
                                flex-wrap: wrap;
                                gap: 0.3rem;
                            ",
                            for skill in &task.required_skills {
                                span {
                                    style: "
                                        font-size: 0.7rem;
                                        padding: 0.1rem 0.4rem;
                                        border-radius: 3px;
                                        background: rgba(108, 92, 231, 0.1);
                                        color: var(--q-primary, #6c5ce7);
                                        border: 1px solid rgba(108, 92, 231, 0.2);
                                    ",
                                    "{skill}"
                                }
                            }
                        }
                    }

                    // Suggested assignee
                    if let Some(ref assignee) = task.suggested_assignee {
                        div {
                            style: "
                                font-size: 0.78rem;
                                color: var(--q-text-secondary, #888);
                            ",
                            "Suggested: {assignee}"
                        }
                    }

                    // Actions
                    div {
                        style: "
                            display: flex;
                            gap: 0.5rem;
                            margin-top: 0.25rem;
                        ",
                        button {
                            onclick: move |_| on_accept.call(()),
                            style: "
                                padding: 0.35rem 0.75rem;
                                border-radius: 6px;
                                border: none;
                                background: var(--q-primary, #6c5ce7);
                                color: #fff;
                                font-size: 0.78rem;
                                font-weight: 500;
                                cursor: pointer;
                            ",
                            "Accept"
                        }
                        if task.can_be_agent {
                            button {
                                onclick: move |_| on_assign_agent.call(()),
                                style: "
                                    padding: 0.35rem 0.75rem;
                                    border-radius: 6px;
                                    border: 1px solid var(--q-accent, #00cec9);
                                    background: transparent;
                                    color: var(--q-accent, #00cec9);
                                    font-size: 0.78rem;
                                    font-weight: 500;
                                    cursor: pointer;
                                ",
                                "Assign to Agent"
                            }
                        }
                    }
                }
            }
        }
    }
}
